{{- if .Values.mailService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stalwart.mailServiceName" . }}
  labels:
    {{- include "stalwart.labels" . | nindent 4 }}
  {{- with .Values.mailService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mailService.type }}
  {{- with .Values.mailService.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . | quote }}
  {{- end }}
  {{- with .Values.mailService.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  selector:
    {{- include "stalwart.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: smtp
      port: {{ .Values.service.ports.smtp }}
      targetPort: smtp
    - name: smtps
      port: {{ .Values.service.ports.smtps }}
      targetPort: smtps
    - name: submission
      port: {{ .Values.service.ports.submission }}
      targetPort: submission
    - name: imap
      port: {{ .Values.service.ports.imap }}
      targetPort: imap
    - name: imaps
      port: {{ .Values.service.ports.imaps }}
      targetPort: imaps
    - name: pop3
      port: {{ .Values.service.ports.pop3 }}
      targetPort: pop3
    - name: pop3s
      port: {{ .Values.service.ports.pop3s }}
      targetPort: pop3s
    - name: sieve
      port: {{ .Values.service.ports.sieve }}
      targetPort: sieve
{{- end }}
