{{- if .Values.configEncryptionKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediumauth.configEncryptionSecretName" . }}
  labels:
    {{- include "mediumauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  TINYAUTH_CONFIG_ENCRYPTION_KEY: {{ .Values.configEncryptionKey.value | quote }}
{{- end }}
