{{/* Append the hardcoded settings */}}
{{- define "paperless-ngx.hardcodedValues" -}}
env:
  PAPERLESS_TIME_ZONE: {{ .Values.env.TZ }}
  PAPERLESS_PORT: {{ quote .Values.service.main.ports.http.port }}

  {{- with .Values.ingress.main }}
  {{- if and .enabled .hosts }}
  PAPERLESS_URL: http{{ if .tls }}s{{ end }}://{{ (first .hosts).host }}
  {{- end }}
  {{- end }}

  {{- with .Values.gateway.main }}
  {{- if and .enabled .hosts }}
  PAPERLESS_URL: {{ .protocol | default "https" }}://{{ (first .hosts).host }}
  {{- end }}
  {{- end }}

  {{- if .Values.postgresql.enabled }}
  {{- with .Values.postgresql }}
  PAPERLESS_DBENGINE: postgresql
  PAPERLESS_DBHOST: {{ $.Release.Name }}-postgresql
  PAPERLESS_DBNAME: {{ .auth.database }}
  PAPERLESS_DBUSER: {{ default "postgres" .auth.username }}
  PAPERLESS_DBPASS:
    secretKeyRef:
      name: {{ .auth.existingSecret | default (printf "%s-postgresql" $.Release.Name) }}
      key: {{ if not .auth.password }}postgres-{{ end }}password
  {{- end }}
  {{- else if .Values.mariadb.enabled }}
  {{- with .Values.mariadb}}
  PAPERLESS_DBENGINE: mariadb
  PAPERLESS_DBHOST: {{ $.Release.Name }}-mariadb
  PAPERLESS_DBNAME: {{ .auth.database }}
  PAPERLESS_DBUSER: {{ .auth.username }}
  PAPERLESS_DBPASS:
    secretKeyRef:
      name: {{ .auth.existingSecret | default (printf "%s-mariadb" $.Release.Name) }}
      key: mariadb-password
  {{- end }}
  {{- end }}

  {{- if .Values.redis.enabled }}
  {{- with .Values.redis }}
  {{- if .auth.enabled }}
  A_REDIS_PASSWORD:
    secretKeyRef:
      name: {{ include "paperless-ngx.redis.secretName" $ }}
      key: {{ .auth.existingSecretPasswordKey | default "redis-password" }}
  PAPERLESS_REDIS: redis://{{ .auth.username }}:$(A_REDIS_PASSWORD)@{{ include "paperless-ngx.redis.serviceName" $ }}:6379
  {{- else }}
  PAPERLESS_REDIS: redis://{{ include "paperless-ngx.redis.serviceName" $ }}:6379
  {{- end }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- define "paperless-ngx.commonValues" -}}
controllers:
  main:
    type: deployment
    containers:
      main:
        image:
          repository: {{ .Values.image.repository }}
          tag: {{ .Values.image.tag }}
          pullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- toYaml (mergeOverwrite (deepCopy .Values.env) ((include "paperless-ngx.hardcodedValues" . | fromYaml).env)) | nindent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.service.main.ports.http.port }}
            protocol: TCP
        probes:
          liveness:
            enabled: true
            type: TCP
            port: {{ .Values.service.main.ports.http.port }}
          readiness:
            enabled: true
            type: TCP
            port: {{ .Values.service.main.ports.http.port }}
          startup:
            enabled: true
            type: TCP
            port: {{ .Values.service.main.ports.http.port }}
            spec:
              failureThreshold: 30
              periodSeconds: 5
service:
  main:
    controller: main
{{- with .Values.persistence }}
persistence:
  {{- range $name, $config := . }}
  {{- if and (kindIs "map" $config) $config.mountPath }}
  {{ $name }}:
    globalMounts:
      - path: {{ $config.mountPath }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "paperless-ngx.commonValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
